site_name: Mi Curriculum
site_author: Lander
site_url: https://Lander-Ortuzar.github.io

theme:
  name: dracula  

nav:
  - Inicio: index.md
  - Sobre MÃ­: sobre-mi.md
  - Proyectos: proyectos.md
  - Contacto: contacto.md

repo_url: https://github.com/lander-ortuzar/Lander.Ortuzar.github.io